// Generated by `seedcord codegen`. Do not edit by hand.
// Run `seedcord codegen` after changing a command's options.

declare module 'seedcord' {
    /**
     * These option types come from your command source. Redeploy your commands to Discord after regenerating,
     * or an interaction from a stale command can return null for an option this file types as non-null.
     */
    interface SlashOptionRegistry {
        maintenance: { notify: { kind: 'user'; required: true }; reason: { kind: 'string'; required: false } };
        probe: { query: { kind: 'string'; required: true; autocomplete: true }; count: { kind: 'integer'; required: false; autocomplete: true }; ratio: { kind: 'number'; required: false; autocomplete: true }; category: { kind: 'string'; required: false; choices: ['books', 'films'] }; exact: { kind: 'boolean'; required: false } };
        'test/confirmable/classic': {};
        'test/confirmable/v2': {};
        throw: {};
    }
    interface UserContextMenuRegistry {
        'View Profile': true;
    }
    interface MessageContextMenuRegistry {
        'Report Message': true;
    }
}

export {};
