// Generated by `seedcord codegen`. Do not edit by hand.
// Run `seedcord codegen` after changing your commands or emoji config.

declare module 'seedcord' {
    interface SlashOptionRegistry {
        defernotice: {};
        feed: {};
        leaderboard: {};
        maintenance: { notify: { kind: 'user'; required: true }; reason: { kind: 'string'; required: false } };
        probe: { query: { kind: 'string'; required: true; autocomplete: true }; count: { kind: 'integer'; required: false; autocomplete: true }; ratio: { kind: 'number'; required: false; autocomplete: true }; category: { kind: 'string'; required: false; choices: ['books', 'films'] }; exact: { kind: 'boolean'; required: false } };
        roster: {};
        'test/confirmable/v2': {};
        throw: {};
    }
    interface UserContextMenuRegistry {
        'View Profile': true;
    }
    interface MessageContextMenuRegistry {
        'Report Message': true;
    }
    interface EmojiMap {
        Cancel: 'application';
        Confirm: 'application';
    }
}

export {};
