// Generated by `seedcord codegen`. Do not edit by hand.
// Run `seedcord codegen` after changing a command's options.

declare module 'seedcord' {
    interface SlashOptionRegistry {
        maintenance: { notify: { kind: 'user'; required: true }; reason: { kind: 'string'; required: false } };
        'test/confirmable/classic': {};
        'test/confirmable/v2': {};
        throw: {};
    }
}

export {};
