import { Linter } from 'eslint';

// a curated subset. unicorn's recommended set enables rules that fight our conventions (no-null,
// no-array-reduce, filename-case, catch-error-name).
export const UNICORN_RULES: Linter.RulesRecord = {
    // correctness / bug-prevention
    'unicorn/error-message': 'error',
    'unicorn/new-for-builtins': 'error',
    'unicorn/throw-new-error': 'error',
    'unicorn/prefer-type-error': 'error',
    'unicorn/no-instanceof-builtins': 'error',
    'unicorn/no-invalid-fetch-options': 'error',
    'unicorn/no-unnecessary-fetch-options': 'error',
    'unicorn/no-unsafe-promise-all-settled-values': 'error',
    'unicorn/no-await-in-promise-methods': 'error',
    'unicorn/no-single-promise-in-promise-methods': 'error',
    'unicorn/no-unnecessary-await': 'error',
    'unicorn/no-array-method-this-argument': 'error',
    'unicorn/no-thenable': 'error',
    'unicorn/no-useless-promise-resolve-reject': 'error',
    'unicorn/no-new-buffer': 'error',
    'unicorn/no-accidental-bitwise-operator': 'error',
    'unicorn/no-invalid-well-known-symbol-methods': 'error',
    'unicorn/require-array-join-separator': 'error',
    'unicorn/require-number-to-fixed-digits-argument': 'error',
    'unicorn/prefer-error-is-error': 'error',

    // modern API (Node 24 / ESNext)
    'unicorn/prefer-node-protocol': 'error',
    'unicorn/prefer-string-slice': 'error',
    'unicorn/prefer-string-starts-ends-with': 'error',
    'unicorn/prefer-string-trim-start-end': 'error',
    'unicorn/prefer-string-replace-all': 'error',
    'unicorn/prefer-string-raw': 'error',
    'unicorn/prefer-string-match-all': 'error',
    'unicorn/prefer-negative-index': 'error',
    'unicorn/prefer-array-some': 'error',
    'unicorn/prefer-array-find': 'error',
    'unicorn/prefer-array-index-of': 'error',
    'unicorn/prefer-array-flat': 'error',
    'unicorn/prefer-array-flat-map': 'error',
    'unicorn/prefer-array-from-async': 'error',
    'unicorn/prefer-includes': 'error',
    'unicorn/prefer-set-has': 'error',
    'unicorn/prefer-set-size': 'error',
    'unicorn/prefer-has-check': 'error',
    'unicorn/prefer-date-now': 'error',
    'unicorn/prefer-regexp-test': 'error',
    'unicorn/prefer-regexp-escape': 'error',
    'unicorn/prefer-number-properties': 'error',
    'unicorn/prefer-number-is-safe-integer': 'error',
    'unicorn/prefer-optional-catch-binding': 'error',
    'unicorn/prefer-spread': 'error',
    'unicorn/prefer-at': 'error',
    'unicorn/prefer-global-this': 'error',
    'unicorn/prefer-native-coercion-functions': 'error',
    'unicorn/prefer-export-from': 'error',
    'unicorn/prefer-modern-math-apis': 'error',
    'unicorn/prefer-math-trunc': 'error',
    'unicorn/prefer-math-min-max': 'error',
    'unicorn/prefer-object-from-entries': 'error',
    'unicorn/prefer-structured-clone': 'error',
    'unicorn/prefer-group-by': 'error',
    'unicorn/prefer-promise-with-resolvers': 'error',
    'unicorn/prefer-promise-try': 'error',

    // clarity / dead-code
    'unicorn/numeric-separators-style': 'error',
    'unicorn/number-literal-case': 'error',
    'unicorn/no-zero-fractions': 'error',
    'unicorn/escape-case': 'error',
    'unicorn/switch-case-braces': 'error',
    'unicorn/switch-case-break-position': 'error',
    'unicorn/consistent-conditional-object-spread': 'error',
    'unicorn/no-typeof-undefined': 'error',
    'unicorn/explicit-length-check': 'error',
    'unicorn/consistent-existence-index-check': 'error',
    'unicorn/no-nested-ternary': 'error',
    'unicorn/no-unnecessary-nested-ternary': 'error',
    'unicorn/no-lonely-if': 'error',
    'unicorn/no-useless-else': 'error',
    'unicorn/prefer-else-if': 'error',
    'unicorn/no-useless-spread': 'error',
    'unicorn/no-useless-fallback-in-spread': 'error',
    'unicorn/no-useless-length-check': 'error',
    'unicorn/no-await-expression-member': 'error',
    'unicorn/prefer-continue': 'error',
    'unicorn/prefer-early-return': 'error',
    'unicorn/no-declarations-before-early-exit': 'error',
    'unicorn/no-unreadable-array-destructuring': 'error',
    'unicorn/prefer-switch': 'error',
    'unicorn/no-static-only-class': 'error',
    'unicorn/text-encoding-identifier-case': 'error'
};
