import { describe, it, expect } from 'vitest';

import { renderSlashRegistry } from '@commands/codegen/renderSlashRegistry';

describe('renderSlashRegistry', () => {
    it('renders a flat command as a declare-module augmentation', () => {
        const output = renderSlashRegistry({
            ban: {
                target: { kind: 'user', required: true },
                reason: { kind: 'string', required: false }
            }
        });

        expect(output).toBe(
            `// Generated by \`seedcord codegen\`. Do not edit by hand.
// Run \`seedcord codegen\` after changing a command's options.

declare module 'seedcord' {
    interface SlashOptionRegistry {
        ban: { target: { kind: 'user'; required: true }; reason: { kind: 'string'; required: false } };
    }
}

export {};
`
        );
    });

    it('sorts routes, quotes subcommand keys, renders choices and empty option sets (the --check contract)', () => {
        const output = renderSlashRegistry({
            'demo/setup': { channel: { kind: 'channel', required: true } },
            config: {
                scope: { kind: 'string', required: true, choices: ['guild', 'global'] },
                level: { kind: 'integer', required: false, choices: [1, 2] }
            },
            ping: {},
            ban: { target: { kind: 'user', required: true } }
        });

        expect(output).toBe(
            `// Generated by \`seedcord codegen\`. Do not edit by hand.
// Run \`seedcord codegen\` after changing a command's options.

declare module 'seedcord' {
    interface SlashOptionRegistry {
        ban: { target: { kind: 'user'; required: true } };
        config: { scope: { kind: 'string'; required: true; choices: ['guild', 'global'] }; level: { kind: 'integer'; required: false; choices: [1, 2] } };
        'demo/setup': { channel: { kind: 'channel'; required: true } };
        ping: {};
    }
}

export {};
`
        );
    });

    it('is byte-stable across renders regardless of input route order', () => {
        const first = renderSlashRegistry({ ban: {}, kick: {} });
        const second = renderSlashRegistry({ kick: {}, ban: {} });
        expect(first).toBe(second);
    });
});
