import { describe, it, expect } from 'vitest';

import { renderSlashRegistry } from '@commands/codegen/renderSlashRegistry';

describe('renderSlashRegistry', () => {
    it('renders a flat command as a declare-module augmentation', () => {
        const output = renderSlashRegistry({
            ban: {
                target: { kind: 'user', required: true },
                reason: { kind: 'string', required: false }
            }
        });

        expect(output).toBe(
            `// Generated by \`seedcord codegen\`. Do not edit by hand.
// Run \`seedcord codegen\` after changing a command's options.

declare module 'seedcord' {
    /**
     * These option types come from your command source. Redeploy your commands to Discord after regenerating,
     * or an interaction from a stale command can return null for an option this file types as non-null.
     */
    interface SlashOptionRegistry {
        ban: { target: { kind: 'user'; required: true }; reason: { kind: 'string'; required: false } };
    }
}

export {};
`
        );
    });

    it('sorts routes, quotes subcommand keys, renders choices and empty option sets (the --check contract)', () => {
        const output = renderSlashRegistry({
            'demo/setup': { channel: { kind: 'channel', required: true } },
            config: {
                scope: { kind: 'string', required: true, choices: ['guild', 'global'] },
                level: { kind: 'integer', required: false, choices: [1, 2] }
            },
            ping: {},
            ban: { target: { kind: 'user', required: true } }
        });

        expect(output).toBe(
            `// Generated by \`seedcord codegen\`. Do not edit by hand.
// Run \`seedcord codegen\` after changing a command's options.

declare module 'seedcord' {
    /**
     * These option types come from your command source. Redeploy your commands to Discord after regenerating,
     * or an interaction from a stale command can return null for an option this file types as non-null.
     */
    interface SlashOptionRegistry {
        ban: { target: { kind: 'user'; required: true } };
        config: { scope: { kind: 'string'; required: true; choices: ['guild', 'global'] }; level: { kind: 'integer'; required: false; choices: [1, 2] } };
        'demo/setup': { channel: { kind: 'channel'; required: true } };
        ping: {};
    }
}

export {};
`
        );
    });

    it('is byte-stable across renders regardless of input route order', () => {
        const first = renderSlashRegistry({ ban: {}, kick: {} });
        const second = renderSlashRegistry({ kick: {}, ban: {} });
        expect(first).toBe(second);
    });

    it('escapes an apostrophe in a string choice value and stays valid TS', () => {
        const output = renderSlashRegistry({
            survey: { answer: { kind: 'string', required: true, choices: ["don't", 'yes'] } }
        });

        expect(output).toContain("choices: ['don\\'t', 'yes']");
        expect(output).toBe(
            `// Generated by \`seedcord codegen\`. Do not edit by hand.
// Run \`seedcord codegen\` after changing a command's options.

declare module 'seedcord' {
    /**
     * These option types come from your command source. Redeploy your commands to Discord after regenerating,
     * or an interaction from a stale command can return null for an option this file types as non-null.
     */
    interface SlashOptionRegistry {
        survey: { answer: { kind: 'string'; required: true; choices: ['don\\'t', 'yes'] } };
    }
}

export {};
`
        );
    });

    it('escapes a backslash in a string choice value', () => {
        const output = renderSlashRegistry({
            path: { dir: { kind: 'string', required: true, choices: ['C:\\Users'] } }
        });

        // input is C:\Users (one backslash); output literal doubles it to C:\\Users
        expect(output).toContain("choices: ['C:\\\\Users']");
    });

    it('escapes both a backslash and an apostrophe together', () => {
        const output = renderSlashRegistry({
            weird: { val: { kind: 'string', required: false, choices: ["it's a \\test"] } }
        });

        // input: it's a \test  ->  literal: 'it\'s a \\test'
        expect(output).toContain("choices: ['it\\'s a \\\\test']");
    });

    it('leaves a double-quote unescaped inside a single-quoted choice literal', () => {
        const output = renderSlashRegistry({
            quote: { phrase: { kind: 'string', required: true, choices: ['say "hi"'] } }
        });

        expect(output).toContain('choices: [\'say "hi"\']');
    });

    it('passes unicode choice values through unchanged', () => {
        const output = renderSlashRegistry({
            lang: { word: { kind: 'string', required: false, choices: ['café', 'naïve'] } }
        });

        expect(output).toContain("choices: ['café', 'naïve']");
    });

    it('escapes a newline in a string choice value', () => {
        const output = renderSlashRegistry({
            note: { tone: { kind: 'string', required: true, choices: ['a\nb'] } }
        });

        expect(output).toContain("choices: ['a\\nb']");
        expect(output).not.toContain('a\nb');
    });

    it('quotes a route key and option name containing a hyphen', () => {
        const output = renderSlashRegistry({
            'my-command': { 'dry-run': { kind: 'boolean', required: false } }
        });

        expect(output).toContain("'my-command': {");
        expect(output).toContain("'dry-run': { kind: 'boolean'; required: false }");
    });

    it('renders the autocomplete flag on autocompletable options', () => {
        const output = renderSlashRegistry({
            search: {
                query: { kind: 'string', required: true, autocomplete: true },
                limit: { kind: 'integer', required: false, autocomplete: true }
            }
        });

        expect(output).toContain(
            "search: { query: { kind: 'string'; required: true; autocomplete: true }; limit: { kind: 'integer'; required: false; autocomplete: true } };"
        );
    });

    it('renders number choices unquoted', () => {
        const output = renderSlashRegistry({
            level: {
                amount: { kind: 'number', required: true, choices: [0, -5, 3.14] },
                tier: { kind: 'integer', required: false, choices: [1, 2] }
            }
        });

        expect(output).toContain('choices: [0, -5, 3.14]');
        expect(output).toContain('choices: [1, 2]');
    });

    it('sorts routes by codepoint deterministically (case-sensitive)', () => {
        const output = renderSlashRegistry({
            z: {},
            a: {},
            Ban: {},
            _a: {},
            Z: {}
        });

        const order = [...output.matchAll(/^        ('?)([\w$/]+)\1: /gm)].map((m) => m[2]);
        // uppercase < underscore < lowercase by UTF-16 codepoint
        expect(order).toEqual(['Ban', 'Z', '_a', 'a', 'z']);
    });

    it('quotes subcommand route keys containing a slash and leaves plain keys unquoted', () => {
        const output = renderSlashRegistry({
            'demo/setup': { channel: { kind: 'channel', required: true } },
            config: { scope: { kind: 'string', required: false } }
        });

        expect(output).toContain("        'demo/setup': {");
        expect(output).toContain('        config: {');
        expect(output).not.toContain("'config'");
    });

    it('quotes an option name that is not a valid identifier', () => {
        const output = renderSlashRegistry({
            link: {
                'user-id': { kind: 'string', required: true },
                target: { kind: 'user', required: false }
            }
        });

        expect(output).toContain("'user-id': { kind: 'string'; required: true }");
        expect(output).toContain("target: { kind: 'user'; required: false }");
    });

    it('renders an empty option set as {}', () => {
        const output = renderSlashRegistry({ ping: {} });

        expect(output).toContain('        ping: {};');
    });

    it('renders an empty registry as the banner, empty interface, and export', () => {
        const output = renderSlashRegistry({});

        expect(output).toBe(
            `// Generated by \`seedcord codegen\`. Do not edit by hand.
// Run \`seedcord codegen\` after changing a command's options.

declare module 'seedcord' {
    /**
     * These option types come from your command source. Redeploy your commands to Discord after regenerating,
     * or an interaction from a stale command can return null for an option this file types as non-null.
     */
    interface SlashOptionRegistry {

    }
}

export {};
`
        );
    });

    it('is byte-stable across input order for a registry with options and choices', () => {
        const first = renderSlashRegistry({
            config: { scope: { kind: 'string', required: true, choices: ['guild', 'global'] } },
            ban: { target: { kind: 'user', required: true } }
        });
        const second = renderSlashRegistry({
            ban: { target: { kind: 'user', required: true } },
            config: { scope: { kind: 'string', required: true, choices: ['guild', 'global'] } }
        });

        expect(first).toBe(second);
    });

    it('renders the exact full-string contract for a realistic multi-route registry', () => {
        const output = renderSlashRegistry({
            'mod/ban': {
                target: { kind: 'user', required: true },
                reason: { kind: 'string', required: false, choices: ["don't", 'other'] }
            },
            settings: {
                scope: { kind: 'string', required: true, choices: ['guild', 'global'] },
                level: { kind: 'integer', required: false, choices: [1, 2] },
                'dry-run': { kind: 'boolean', required: false }
            },
            ping: {}
        });

        expect(output).toBe(
            `// Generated by \`seedcord codegen\`. Do not edit by hand.
// Run \`seedcord codegen\` after changing a command's options.

declare module 'seedcord' {
    /**
     * These option types come from your command source. Redeploy your commands to Discord after regenerating,
     * or an interaction from a stale command can return null for an option this file types as non-null.
     */
    interface SlashOptionRegistry {
        'mod/ban': { target: { kind: 'user'; required: true }; reason: { kind: 'string'; required: false; choices: ['don\\'t', 'other'] } };
        ping: {};
        settings: { scope: { kind: 'string'; required: true; choices: ['guild', 'global'] }; level: { kind: 'integer'; required: false; choices: [1, 2] }; 'dry-run': { kind: 'boolean'; required: false } };
    }
}

export {};
`
        );
    });
});
