import { describe, it, expect } from 'vitest';

import { renderAugmentation } from '@commands/codegen/renderAugmentation';

import type { SlashTables } from '@commands/codegen/AugmentationBuilder';

// most assertions only exercise the slash tables, so wrap them with empty context-menu sets.
function renderSlash(slash: SlashTables): string {
    return renderAugmentation({ slash, userContextMenus: [], messageContextMenus: [], emojis: {} });
}

describe('renderAugmentation', () => {
    it('renders a flat command as a declare-module augmentation', () => {
        const output = renderSlash({
            ban: {
                target: { kind: 'user', required: true },
                reason: { kind: 'string', required: false }
            }
        });

        expect(output).toBe(
            `// Generated by \`seedcord codegen\`. Do not edit by hand.
// Run \`seedcord codegen\` after changing your commands or emoji config.

declare module 'seedcord' {
    interface SlashOptionRegistry {
        ban: { target: { kind: 'user'; required: true }; reason: { kind: 'string'; required: false } };
    }
    interface UserContextMenuRegistry {

    }
    interface MessageContextMenuRegistry {

    }
    interface EmojiMap {

    }
}

export {};
`
        );
    });

    it('sorts routes, quotes subcommand keys, renders choices and empty option sets (the --check contract)', () => {
        const output = renderSlash({
            'demo/setup': { channel: { kind: 'channel', required: true } },
            config: {
                scope: { kind: 'string', required: true, choices: ['guild', 'global'] },
                level: { kind: 'integer', required: false, choices: [1, 2] }
            },
            ping: {},
            ban: { target: { kind: 'user', required: true } }
        });

        expect(output).toBe(
            `// Generated by \`seedcord codegen\`. Do not edit by hand.
// Run \`seedcord codegen\` after changing your commands or emoji config.

declare module 'seedcord' {
    interface SlashOptionRegistry {
        ban: { target: { kind: 'user'; required: true } };
        config: { scope: { kind: 'string'; required: true; choices: ['guild', 'global'] }; level: { kind: 'integer'; required: false; choices: [1, 2] } };
        'demo/setup': { channel: { kind: 'channel'; required: true } };
        ping: {};
    }
    interface UserContextMenuRegistry {

    }
    interface MessageContextMenuRegistry {

    }
    interface EmojiMap {

    }
}

export {};
`
        );
    });

    it('is byte-stable across renders regardless of input route order', () => {
        const first = renderSlash({ ban: {}, kick: {} });
        const second = renderSlash({ kick: {}, ban: {} });
        expect(first).toBe(second);
    });

    it('escapes an apostrophe in a string choice value and stays valid TS', () => {
        const output = renderSlash({
            survey: { answer: { kind: 'string', required: true, choices: ["don't", 'yes'] } }
        });

        expect(output).toContain(String.raw`choices: ['don\'t', 'yes']`);
    });

    it('escapes a backslash in a string choice value', () => {
        const output = renderSlash({
            path: { dir: { kind: 'string', required: true, choices: [String.raw`C:\Users`] } }
        });

        // input is C:\Users (one backslash); output literal doubles it to C:\\Users
        expect(output).toContain(String.raw`choices: ['C:\\Users']`);
    });

    it('escapes both a backslash and an apostrophe together', () => {
        const output = renderSlash({
            weird: { val: { kind: 'string', required: false, choices: [String.raw`it's a \test`] } }
        });

        // input: it's a \test  ->  literal: 'it\'s a \\test'
        expect(output).toContain(String.raw`choices: ['it\'s a \\test']`);
    });

    it('leaves a double-quote unescaped inside a single-quoted choice literal', () => {
        const output = renderSlash({
            quote: { phrase: { kind: 'string', required: true, choices: ['say "hi"'] } }
        });

        expect(output).toContain('choices: [\'say "hi"\']');
    });

    it('passes unicode choice values through unchanged', () => {
        const output = renderSlash({
            lang: { word: { kind: 'string', required: false, choices: ['café', 'naïve'] } }
        });

        expect(output).toContain("choices: ['café', 'naïve']");
    });

    it('escapes a newline in a string choice value', () => {
        const output = renderSlash({
            note: { tone: { kind: 'string', required: true, choices: ['a\nb'] } }
        });

        expect(output).toContain(String.raw`choices: ['a\nb']`);
        expect(output).not.toContain('a\nb');
    });

    it('quotes a route key and option name containing a hyphen', () => {
        const output = renderSlash({
            'my-command': { 'dry-run': { kind: 'boolean', required: false } }
        });

        expect(output).toContain("'my-command': {");
        expect(output).toContain("'dry-run': { kind: 'boolean'; required: false }");
    });

    it('renders the autocomplete flag on autocompletable options', () => {
        const output = renderSlash({
            search: {
                query: { kind: 'string', required: true, autocomplete: true },
                limit: { kind: 'integer', required: false, autocomplete: true }
            }
        });

        expect(output).toContain(
            "search: { query: { kind: 'string'; required: true; autocomplete: true }; limit: { kind: 'integer'; required: false; autocomplete: true } };"
        );
    });

    it('renders number choices unquoted', () => {
        const output = renderSlash({
            level: {
                amount: { kind: 'number', required: true, choices: [0, -5, 3.14] },
                tier: { kind: 'integer', required: false, choices: [1, 2] }
            }
        });

        expect(output).toContain('choices: [0, -5, 3.14]');
        expect(output).toContain('choices: [1, 2]');
    });

    it('sorts routes by codepoint deterministically (case-sensitive)', () => {
        const output = renderSlash({
            z: {},
            a: {},
            Ban: {},
            _a: {},
            Z: {}
        });

        const order = [...output.matchAll(/^        ('?)([\w$/]+)\1: /gm)].map((m) => m[2]);
        // uppercase < underscore < lowercase by UTF-16 codepoint
        expect(order).toEqual(['Ban', 'Z', '_a', 'a', 'z']);
    });

    it('quotes subcommand route keys containing a slash and leaves plain keys unquoted', () => {
        const output = renderSlash({
            'demo/setup': { channel: { kind: 'channel', required: true } },
            config: { scope: { kind: 'string', required: false } }
        });

        expect(output).toContain("        'demo/setup': {");
        expect(output).toContain('        config: {');
        expect(output).not.toContain("'config'");
    });

    it('quotes an option name that is not a valid identifier', () => {
        const output = renderSlash({
            link: {
                'user-id': { kind: 'string', required: true },
                target: { kind: 'user', required: false }
            }
        });

        expect(output).toContain("'user-id': { kind: 'string'; required: true }");
        expect(output).toContain("target: { kind: 'user'; required: false }");
    });

    it('renders an empty option set as {}', () => {
        const output = renderSlash({ ping: {} });

        expect(output).toContain('        ping: {};');
    });

    it('renders an empty registry as the banner, three empty interfaces, and export', () => {
        const output = renderAugmentation({ slash: {}, userContextMenus: [], messageContextMenus: [], emojis: {} });

        expect(output).toBe(
            `// Generated by \`seedcord codegen\`. Do not edit by hand.
// Run \`seedcord codegen\` after changing your commands or emoji config.

declare module 'seedcord' {
    interface SlashOptionRegistry {

    }
    interface UserContextMenuRegistry {

    }
    interface MessageContextMenuRegistry {

    }
    interface EmojiMap {

    }
}

export {};
`
        );
    });

    it('is byte-stable across input order for a registry with options and choices', () => {
        const first = renderSlash({
            config: { scope: { kind: 'string', required: true, choices: ['guild', 'global'] } },
            ban: { target: { kind: 'user', required: true } }
        });
        const second = renderSlash({
            ban: { target: { kind: 'user', required: true } },
            config: { scope: { kind: 'string', required: true, choices: ['guild', 'global'] } }
        });

        expect(first).toBe(second);
    });

    it('renders the exact full-string contract for a realistic multi-route registry', () => {
        const output = renderSlash({
            'mod/ban': {
                target: { kind: 'user', required: true },
                reason: { kind: 'string', required: false, choices: ["don't", 'other'] }
            },
            settings: {
                scope: { kind: 'string', required: true, choices: ['guild', 'global'] },
                level: { kind: 'integer', required: false, choices: [1, 2] },
                'dry-run': { kind: 'boolean', required: false }
            },
            ping: {}
        });

        expect(output).toBe(
            `// Generated by \`seedcord codegen\`. Do not edit by hand.
// Run \`seedcord codegen\` after changing your commands or emoji config.

declare module 'seedcord' {
    interface SlashOptionRegistry {
        'mod/ban': { target: { kind: 'user'; required: true }; reason: { kind: 'string'; required: false; choices: ['don\\'t', 'other'] } };
        ping: {};
        settings: { scope: { kind: 'string'; required: true; choices: ['guild', 'global'] }; level: { kind: 'integer'; required: false; choices: [1, 2] }; 'dry-run': { kind: 'boolean'; required: false } };
    }
    interface UserContextMenuRegistry {

    }
    interface MessageContextMenuRegistry {

    }
    interface EmojiMap {

    }
}

export {};
`
        );
    });

    it('renders user and message context-menu names into their own interfaces, codepoint-sorted', () => {
        const output = renderAugmentation({
            slash: {},
            userContextMenus: ['View Profile', 'Report'],
            messageContextMenus: ['Report Message', 'Pin'],
            emojis: {}
        });

        expect(output).toBe(
            `// Generated by \`seedcord codegen\`. Do not edit by hand.
// Run \`seedcord codegen\` after changing your commands or emoji config.

declare module 'seedcord' {
    interface SlashOptionRegistry {

    }
    interface UserContextMenuRegistry {
        Report: true;
        'View Profile': true;
    }
    interface MessageContextMenuRegistry {
        Pin: true;
        'Report Message': true;
    }
    interface EmojiMap {

    }
}

export {};
`
        );
    });

    it('emits the same name in both interfaces when a user and message command share it', () => {
        const output = renderAugmentation({
            slash: {},
            userContextMenus: ['Report'],
            messageContextMenus: ['Report'],
            emojis: {}
        });

        expect(output).toContain('    interface UserContextMenuRegistry {\n        Report: true;\n    }');
        expect(output).toContain('    interface MessageContextMenuRegistry {\n        Report: true;\n    }');
    });

    it('escapes an apostrophe in a context-menu name', () => {
        const output = renderAugmentation({
            slash: {},
            userContextMenus: ["Tony's Profile"],
            messageContextMenus: [],
            emojis: {}
        });

        expect(output).toContain(String.raw`        'Tony\'s Profile': true;`);
    });

    it('leaves an identifier-safe context-menu name unquoted', () => {
        const output = renderAugmentation({
            slash: {},
            userContextMenus: ['Report'],
            messageContextMenus: [],
            emojis: {}
        });

        expect(output).toContain('        Report: true;');
        expect(output).not.toContain("'Report'");
    });

    it('is byte-stable across input order for the context-menu sets', () => {
        const first = renderAugmentation({
            slash: {},
            userContextMenus: ['View Profile', 'Report'],
            messageContextMenus: ['Pin', 'Report Message'],
            emojis: {}
        });
        const second = renderAugmentation({
            slash: {},
            userContextMenus: ['Report', 'View Profile'],
            messageContextMenus: ['Report Message', 'Pin'],
            emojis: {}
        });

        expect(first).toBe(second);
    });
});

describe('renderAugmentation emoji rows', () => {
    it('renders emoji keys into EmojiMap, application for a string config and guild for a tuple config', () => {
        const output = renderAugmentation({
            slash: {},
            userContextMenus: [],
            messageContextMenus: [],
            emojis: { Confirm: 'string', Lol: 'tuple', Cancel: 'string' }
        });

        expect(output).toContain(
            "    interface EmojiMap {\n        Cancel: 'application';\n        Confirm: 'application';\n        Lol: 'guild';\n    }"
        );
    });

    it('quotes an emoji key that is not a valid identifier', () => {
        const output = renderAugmentation({
            slash: {},
            userContextMenus: [],
            messageContextMenus: [],
            emojis: { 'thumbs-up': 'string' }
        });

        expect(output).toContain("        'thumbs-up': 'application';");
    });

    it('escapes an apostrophe in an emoji key', () => {
        const output = renderAugmentation({
            slash: {},
            userContextMenus: [],
            messageContextMenus: [],
            emojis: { "Tony's": 'string' }
        });

        expect(output).toContain(String.raw`        'Tony\'s': 'application';`);
    });

    it('is byte-stable across input order for the emoji keys', () => {
        const first = renderAugmentation({
            slash: {},
            userContextMenus: [],
            messageContextMenus: [],
            emojis: { Confirm: 'string', Lol: 'tuple' }
        });
        const second = renderAugmentation({
            slash: {},
            userContextMenus: [],
            messageContextMenus: [],
            emojis: { Lol: 'tuple', Confirm: 'string' }
        });

        expect(first).toBe(second);
    });
});
