// Generated by `seedcord codegen`. Do not edit by hand.
// Run `seedcord codegen` after changing your commands, plugins, or emoji config.

import type Bot from './bot';

// prettier-ignore
declare module '@seedcord/http' {
    interface Core {
        cause: (typeof Bot)['cause'];
        coded: (typeof Bot)['coded'];
        longstack: (typeof Bot)['longstack'];
        nested: (typeof Bot)['nested'];
        plain: (typeof Bot)['plain'];
        string: (typeof Bot)['string'];
    }
    interface SlashOptionRegistry {
        ping: { detailed: { kind: 'boolean'; required: false } };
    }
    interface UserContextMenuRegistry {

    }
    interface MessageContextMenuRegistry {

    }
    interface EmojiMap {

    }
}

export {};
