// Generated by `seedcord codegen`. Do not edit by hand.
// Run `seedcord codegen` after changing your commands, plugins, or emoji config.

import type Bot from './bot';

// prettier-ignore
declare module '@seedcord/http' {
    interface Core {
        stats: (typeof Bot)['stats'];
    }
    interface SlashRegistry {
        ping: { options: { detailed: { kind: 'boolean'; required: false } }; cache: 'cached' };
        roll: { options: { sides: { kind: 'integer'; required: false } }; cache: 'cached' };
    }
    interface UserContextMenuRegistry {

    }
    interface MessageContextMenuRegistry {

    }
    interface EmojiMap {

    }
}

export {};
