// Generated by `seedcord codegen`. Do not edit by hand.
// Run `seedcord codegen` after changing your commands or emoji config.

// prettier-ignore
declare module '@seedcord/http' {
    interface SlashOptionRegistry {
        ping: { note: { kind: 'string'; required: true } };
    }
    interface UserContextMenuRegistry {

    }
    interface MessageContextMenuRegistry {

    }
    interface EmojiMap {

    }
}

export {};
