// Comprehensive, real seedcord feature inventory for the hero marquee (audited from the package barrels).
export const FEATURES = [
    'typed slash commands',
    'typed slash options',
    'subcommand routing',
    'autocomplete handlers',
    'user context menus',
    'message context menus',
    'typed command mentions',
    'typed emojis',
    '100-char customId codec',
    'ComponentsV2 builders',
    'embed builders',
    'button handlers',
    'select menu handlers',
    'modal handlers',
    'confirmation prompts',
    'composable gates',
    'OwnerOnly gate',
    'GuildOnly / DmOnly gates',
    'RequirePermissions gate',
    'RequireBotPermissions gate',
    'RequireRole gate',
    'Nsfw gate',
    'IgnoreBots gate',
    'and / or gate combinators',
    'custom gates',
    'effect gates',
    'sliding-window rate limiter',
    'cooldown gate',
    'scoped logger',
    'multi-channel log routing',
    'rotating file transports',
    'custom log sinks',
    'HTTP health check',
    '7-phase coordinated startup',
    '5-phase coordinated shutdown',
    'SIGTERM / SIGINT handling',
    'typed pub/sub bus',
    'webhook fault reporters',
    'interaction middleware',
    'event middleware',
    'middleware priority ordering',
    'one-shot event handlers',
    'multi-event handlers',
    'typed waitFor',
    'Notice / Fault / Silence errors',
    'fault tracking UUID',
    'configurable default error',
    'token validation at startup',
    'stale-registry runtime guard',
    'Vite SSR hot module replacement',
    'background tsc watch',
    'Ink full-screen dev UI',
    'seedcord build',
    'seedcord codegen',
    'seedcord commands wizard',
    'plugin system',
    'KyselyPg plugin',
    'Mongo plugin',
    'ReplyResponse (ComponentsV2)',
    'reply / edit / followUp routing',
    'file attachments in replies',
    'declaration-merge DI',
    'BotEvents typed stream',
    'EpochMs / EpochSec branded types',
    'parseDuration utility',
    'generateAsciiTable utility',
    'assertNever utility'
] as const;
