// Real seedcord feature inventory for the marquee, consolidated to feature areas (every area, not every minute sub-feature).
export const FEATURES = [
    'typed slash commands',
    'typed slash options',
    'subcommand routing',
    'autocomplete handlers',
    'context menu commands',
    'typed command mentions',
    'typed emojis',
    'typed customId codec',
    'ComponentsV2 first',
    'button & select handlers',
    'modal handlers',
    'confirmation prompts',
    'permission & role gates',
    'guild / DM / NSFW gates',
    'cooldown gate',
    'sliding-window rate limiter',
    'composable custom & effect gates',
    'Notice / Fault / Silence error flow',
    'webhook fault reporters',
    'coordinated startup & shutdown',
    'HTTP health check',
    'scoped logger + transports',
    'typed pub/sub bus',
    'interaction & event middleware',
    'typed event handlers & waitFor',
    'Vite HMR hot reload, gateway stays alive',
    'Ink dev UI',
    'seedcord codegen',
    'seedcord commands wizard',
    'plugin system',
    'Postgres & Mongo plugins'
] as const;
