export const FEATURES = [
    'gateway & http transports',
    'typed slash commands',
    'typed slash options',
    'subcommand routing',
    'autocomplete handlers',
    'context menu commands',
    'typed command mentions',
    'typed emojis',
    'typed customId codec',
    'ComponentsV2 first',
    'button & selectmenu handlers',
    'modal handlers',
    'confirmation prompts',
    'restart-proof pagination',
    'permission & role gates',
    'guild / DM / NSFW gates',
    'cooldown gate',
    'sliding-window rate limiter',
    'composable custom & effect gates',
    'Notice / Fault / Silence error flow',
    'webhook fault reporters',
    'coordinated startup & shutdown',
    'HTTP health check',
    'logger with channels & sinks',
    'typed pub/sub bus',
    'interaction & event middleware',
    'typed event handlers & waitFor',
    'Vite HMR hot reload, gateway stays alive',
    'Ink dev UI',
    'cloudflared dev tunnel',
    'project scaffolding',
    'seedcord codegen',
    'seedcord commands wizard',
    'typed plugins',
    'Postgres & Mongo plugins',
    'eslint rules for discord.js'
] as const;
