import type { RouteOptions, SlashTables } from './SlashTableGenerator';
import type { SlashOption } from '@seedcord/types';

const BANNER = `// Generated by \`seedcord codegen\`. Do not edit by hand.
// Run \`seedcord codegen\` after changing a command's options.`;

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

/**
 * Renders the slash tables into the committed `declare module 'seedcord'` file. Routes are sorted so the
 * output is stable across filesystems, option order follows the builder (a meaningful change to regenerate).
 * The result is byte-stable so `seedcord codegen --check` can diff it directly.
 */
export function renderSlashRegistry(tables: SlashTables): string {
    const rows = Object.entries(tables)
        .sort(([first], [second]) => compare(first, second))
        .map(([route, options]) => `        ${renderKey(route)}: ${renderRow(options)};`)
        .join('\n');

    return `${BANNER}\n\ndeclare module 'seedcord' {\n    interface SlashOptionRegistry {\n${rows}\n    }\n}\n\nexport {};\n`;
}

function renderRow(options: RouteOptions): string {
    const entries = Object.entries(options);
    if (entries.length === 0) return '{}';
    return `{ ${entries.map(([name, opt]) => `${renderKey(name)}: ${renderOption(opt)}`).join('; ')} }`;
}

function renderOption(opt: SlashOption): string {
    const parts = [`kind: '${opt.kind}'`, `required: ${opt.required}`];
    if (opt.choices && opt.choices.length > 0) parts.push(`choices: [${opt.choices.map(renderChoice).join(', ')}]`);
    return `{ ${parts.join('; ')} }`;
}

function renderChoice(value: string | number): string {
    return typeof value === 'string' ? `'${value}'` : String(value);
}

function renderKey(name: string): string {
    return IDENTIFIER.test(name) ? name : `'${name}'`;
}

function compare(first: string, second: string): number {
    if (first < second) return -1;
    return first > second ? 1 : 0;
}
