import type { RouteOptions, SlashTables } from './SlashTableGenerator';
import type { SlashOption } from '@seedcord/types';

const BANNER = `// Generated by \`seedcord codegen\`. Do not edit by hand.
// Run \`seedcord codegen\` after changing a command's options.`;

const DISCLAIMER = `    /**
     * These option types come from your command source. Redeploy your commands to Discord after regenerating,
     * or an interaction from a stale command can return null for an option this file types as non-null.
     */`;

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
const CONTROL_CHAR = 0x20;
const HEX_RADIX = 16;

/**
 * Renders the slash tables into the committed `declare module 'seedcord'` file. Routes are sorted so the
 * output is stable across filesystems, option order follows the builder (a meaningful change to regenerate).
 * The result is byte-stable so `seedcord codegen --check` can diff it directly.
 */
export function renderSlashRegistry(tables: SlashTables): string {
    const rows = Object.entries(tables)
        .sort(([first], [second]) => compare(first, second))
        .map(([route, options]) => `        ${renderKey(route)}: ${renderRow(options)};`)
        .join('\n');

    return `${BANNER}\n\ndeclare module 'seedcord' {\n${DISCLAIMER}\n    interface SlashOptionRegistry {\n${rows}\n    }\n}\n\nexport {};\n`;
}

function renderRow(options: RouteOptions): string {
    const entries = Object.entries(options);
    if (entries.length === 0) return '{}';
    return `{ ${entries.map(([name, opt]) => `${renderKey(name)}: ${renderOption(opt)}`).join('; ')} }`;
}

function renderOption(opt: SlashOption): string {
    const parts = [`kind: '${opt.kind}'`, `required: ${opt.required}`];
    if (opt.choices && opt.choices.length > 0) parts.push(`choices: [${opt.choices.map(renderChoice).join(', ')}]`);
    if (opt.autocomplete) parts.push('autocomplete: true');
    return `{ ${parts.join('; ')} }`;
}

// a choice value is an arbitrary Discord string, so escape backslashes, quotes, and control chars or it emits invalid TS.
function renderChoice(value: string | number): string {
    if (typeof value !== 'string') return String(value);
    let escaped = '';
    for (const char of value) {
        const code = char.charCodeAt(0);
        if (char === '\\') escaped += '\\\\';
        else if (char === "'") escaped += "\\'";
        else if (char === '\n') escaped += '\\n';
        else if (char === '\r') escaped += '\\r';
        else if (char === '\t') escaped += '\\t';
        else if (code < CONTROL_CHAR) escaped += `\\x${code.toString(HEX_RADIX).padStart(2, '0')}`;
        else escaped += char;
    }
    return `'${escaped}'`;
}

function renderKey(name: string): string {
    return IDENTIFIER.test(name) ? name : `'${name}'`;
}

function compare(first: string, second: string): number {
    if (first < second) return -1;
    return first > second ? 1 : 0;
}
