import type { EmojiKinds, Augmentation, RouteOptions, SlashTables } from './AugmentationBuilder';
import type { SlashOption } from '@seedcord/core';

const BANNER = `// Generated by \`seedcord codegen\`. Do not edit by hand.
// Run \`seedcord codegen\` after changing your commands or emoji config.`;

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
const CONTROL_CHAR = 0x20;
const HEX_RADIX = 16;

/**
 * Renders the built augmentations into the committed `declare module 'seedcord'` file, the slash option
 * tables, the user and message context-menu name registries, and the emoji map, all in one block. Keys are
 * sorted so the output is stable across filesystems. The result is byte-stable so `seedcord codegen --check`
 * can diff it directly.
 */
export function renderAugmentation(registry: Augmentation): string {
    return (
        `${BANNER}\n\ndeclare module 'seedcord' {\n` +
        `    interface SlashOptionRegistry {\n${renderSlashRows(registry.slash)}\n    }\n` +
        `    interface UserContextMenuRegistry {\n${renderContextMenuRows(registry.userContextMenus)}\n    }\n` +
        `    interface MessageContextMenuRegistry {\n${renderContextMenuRows(registry.messageContextMenus)}\n    }\n` +
        `    interface EmojiMap {\n${renderEmojiRows(registry.emojis)}\n    }\n` +
        `}\n\nexport {};\n`
    );
}

function renderSlashRows(tables: SlashTables): string {
    return Object.entries(tables)
        .sort(([first], [second]) => compare(first, second))
        .map(([route, options]) => `        ${renderKey(route)}: ${renderRow(options)};`)
        .join('\n');
}

// an empty kind renders the blank-body form (matching the slash registry), so the interface stays present
// and `keyof` resolves to `never` rather than the file omitting it.
function renderContextMenuRows(names: readonly string[]): string {
    return [...names]
        .sort(compare)
        .map((name) => `        ${renderName(name)}: true;`)
        .join('\n');
}

// InjectedEmojiMap reads this tag to type Emojis.X as GuildEmoji vs ApplicationEmoji.
function renderEmojiRows(emojis: EmojiKinds): string {
    return Object.entries(emojis)
        .sort(([first], [second]) => compare(first, second))
        .map(([key, kind]) => `        ${renderName(key)}: '${kind === 'tuple' ? 'guild' : 'application'}';`)
        .join('\n');
}

function renderRow(options: RouteOptions): string {
    const entries = Object.entries(options);
    if (entries.length === 0) return '{}';
    return `{ ${entries.map(([name, opt]) => `${renderKey(name)}: ${renderOption(opt)}`).join('; ')} }`;
}

function renderOption(opt: SlashOption): string {
    const parts = [`kind: '${opt.kind}'`, `required: ${opt.required}`];
    if (opt.choices && opt.choices.length > 0) parts.push(`choices: [${opt.choices.map(renderChoice).join(', ')}]`);
    if (opt.autocomplete) parts.push('autocomplete: true');
    return `{ ${parts.join('; ')} }`;
}

function renderChoice(value: string | number): string {
    if (typeof value !== 'string') return String(value);
    return `'${escapeLiteral(value)}'`;
}

// a slash route or option name is restricted to Discord's name charset, so quoting alone is enough. A
// context-menu name allows spaces, mixed case, and apostrophes, so its quoted form must escape the body.
function renderName(name: string): string {
    return IDENTIFIER.test(name) ? name : `'${escapeLiteral(name)}'`;
}

function renderKey(name: string): string {
    return IDENTIFIER.test(name) ? name : `'${name}'`;
}

// escape backslashes, single quotes, and control chars or the value emits invalid TS inside a single-quoted literal.
function escapeLiteral(value: string): string {
    let escaped = '';
    for (const char of value) {
        const code = char.charCodeAt(0);
        switch (char) {
            case '\\': {
                escaped += '\\\\';
                break;
            }
            case "'": {
                escaped += String.raw`\'`;
                break;
            }
            case '\n': {
                escaped += String.raw`\n`;
                break;
            }
            case '\r': {
                escaped += String.raw`\r`;
                break;
            }
            case '\t': {
                escaped += String.raw`\t`;
                break;
            }
            default: {
                if (code < CONTROL_CHAR) escaped += String.raw`\x${code.toString(HEX_RADIX).padStart(2, '0')}`;
                else escaped += char;
            }
        }
    }
    return escaped;
}

function compare(first: string, second: string): number {
    if (first < second) return -1;
    return first > second ? 1 : 0;
}
