export const typedDxCommand = `import {
    RegisterCommand, BuilderComponent
} from '@seedcord/gateway';

@RegisterCommand('global')
export class SearchCommand extends
    BuilderComponent<'command'> {
    constructor() {
        super('command');

        this.instance
            .setName('search')
            .setDescription('Search the catalog')
            .addStringOption((o) =>
                o
                    .setName('category')
                    .setDescription('What to look through')
                    .setRequired(true)
                    .addChoices(
                        { name: 'Books', value: 'books' },
                        { name: 'Films', value: 'films' }
                    )
            );
    }
}`;

export const typedDxHandler = `import {
    SlashRoute, SlashHandler
} from '@seedcord/gateway';

@SlashRoute('search')
export class SearchHandler extends
    SlashHandler<'search'> {
    public async execute(): Promise<void> {
        // generated accessor, no cast,
        // no null check
        const category =
            this.options.getString('category');
        //    ^?  'books' | 'films'

        await this.reply(\`Searching \${category}\`);
    }
}`;

export const resolvedCheck = `const category = getString('category');
//    ^?  'books' | 'films'

const valid: 'books' | 'films' = category; // OK
const wrong: 'audio' = category; // Error 2322`;

export const beforeRawDjs = `// build it, route to the subcommand,
// validate, all by hand
const data = new SlashCommandBuilder()
    .setName('library')
    .addSubcommand((s) =>
        s.setName('search').addStringOption(...)
    );

client.on(Events.InteractionCreate, async (i) => {
    if (!i.isChatInputCommand()) return;
    if (i.commandName !== 'library') return;
    if (i.options.getSubcommand() !== 'search') return;

    const raw = i.options.getString('query');
    if (raw === null) throw new Error('required');
    const query = raw as 'fiction' | 'nonfiction'; // cast

    // ...manual guard and cooldown checks...
    await i.reply(\`Searching for \${query}\`);
});

// plus a REST register script, plus a
// switch per subcommand,
// plus a full process restart on every edit`;

export const afterSeedcord = `import {
    SlashRoute, SlashHandler,
    Gated, GuildOnly
} from '@seedcord/gateway';

@Gated(GuildOnly())
@SlashRoute('library/search')
export class SearchHandler extends
    SlashHandler<'library/search'> {
    public async execute() {
        const query = this.options.getString('query');
        //    ^?  'fiction' | 'nonfiction'

        await this.reply(\`Searching for \${query}\`);
    }
}

// the route, registration and guards are done.
// edit, save, hot reload, the gateway stays up.`;

export const codecComponent = `import {
    BuilderComponent, CustomId
} from '@seedcord/gateway';

export const Roles = new CustomId('roles')
    .snowflake('memberId')
    .oneOf('mode', ['add', 'remove']);

export class RolePicker extends
    BuilderComponent<'menu_role'> {
    constructor(memberId: string) {
        super('menu_role');
        const id = Roles.encode({
            memberId,
            mode: 'add'
        });
        this.instance
            .setPlaceholder('Roles to add')
            .setCustomId(id);
    }
}`;

export const codecHandler = `import {
    SelectMenuHandler,
    SelectMenuKind,
    SelectMenuRoute
} from '@seedcord/gateway';
import { Roles } from '#components/role-picker';

@SelectMenuRoute(SelectMenuKind.Role, Roles)
export class RolePickerHandler extends SelectMenuHandler<
    SelectMenuKind.Role,
    [typeof Roles]
> {
    public async execute(): Promise<void> {
        const { memberId, mode } = this.params;
        // memberId: string, mode: 'add' | 'remove'
        const picked = this.event.values;
        await this.reply(
            \`\${mode} \${picked.length} <@\${memberId}>\`
        );
    }
}`;

export const codegenOutput = `// Generated by \`seedcord codegen\`. Do not edit by hand.
declare module '@seedcord/gateway' {
    interface SlashRegistry {
        search: {
            options: {
                category: {
                    kind: 'string';
                    required: true;
                    choices: ['books', 'films'];
                };
            };
            cache: 'cached';
        };
    }
}`;

export const startTerminal = `$ pnpm create seedcord my-bot # scaffold a typed bot
$ cd my-bot
$ seedcord dev # tui | hot reload, gateway alive

# bot online, every slash option fully typed`;

export const gatesSample = `import {
    Gated, and, or,
    GuildOnly, OwnerOnly, RequireRole,
    SlashRoute, SlashHandler
} from '@seedcord/gateway';

@Gated(or(
    OwnerOnly(),
    and(GuildOnly(), RequireRole(modRoleId))
))
@SlashRoute('ban')
export class BanHandler extends SlashHandler<'ban'> {
    public async execute() {
        // an owner, or a mod inside a guild, gets through
    }
}`;

export const pluginSource = `import { Plugin } from '@seedcord/gateway';
import type { CoreBase } from '@seedcord/core';

export class Uptime extends Plugin {
    public startedAt = 0;

    constructor(
        host: CoreBase,
        private readonly label: string
    ) {
        super(host);
    }

    public async init(): Promise<void> {
        this.startedAt = Date.now();
        this.logger.info(\`\${this.label} up\`);
    }
}`;

export const pluginAttach = `import { Uptime } from '#plugins/uptime';

export default new Seedcord({
    // ...your bot config
}).attach('uptime', Uptime, 'my-bot');`;

export const pluginGenerated = `// Generated by \`seedcord codegen\`. Do not edit by hand.
import type Bot from './bot';

declare module '@seedcord/gateway' {
    interface Core {
        uptime: (typeof Bot)['uptime'];
    }
}`;
