import type { EmojiKinds, Augmentation, ContextMenuTables, RouteOptions, SlashTables } from './AugmentationBuilder';
import type { SlashOption, SlashRouteEntry } from '@seedcord/core/internal';

const BANNER = `// Generated by \`seedcord codegen\`. Do not edit by hand.
// Run \`seedcord codegen\` after changing your commands, plugins, or emoji config.`;

const BOT_BINDING = 'Bot';

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
const CONTROL_CHAR = 0x20;
const HEX_RADIX = 16;

interface AttachedPlugins {
    readonly specifier: string; // relative to the generated file at config.root
    readonly keys: readonly string[];
}

export function renderAugmentation(registry: Augmentation, target: string, plugins?: AttachedPlugins): string {
    const keys = [...(plugins?.keys ?? [])].sort(compare);
    const attached = plugins !== undefined && keys.length > 0;
    const botImport = attached ? `import type ${BOT_BINDING} from '${escapeLiteral(plugins.specifier)}';\n\n` : '';
    const coreRows = attached ? `    interface Core {\n${renderPluginRows(keys)}\n    }\n` : '';

    // prettier-ignore binds to the next statement, and the declare module is the whole file
    const header = `${BANNER}\n\n${botImport}// prettier-ignore\ndeclare module '${target}' {\n`;

    return (
        `${header + coreRows}    interface SlashRegistry {\n${renderSlashRows(registry.slash)}\n    }\n` +
        `    interface UserContextMenuRegistry {\n${renderContextMenuRows(registry.userContextMenus)}\n    }\n` +
        `    interface MessageContextMenuRegistry {\n${renderContextMenuRows(registry.messageContextMenus)}\n    }\n` +
        `    interface EmojiMap {\n${renderEmojiRows(registry.emojis)}\n    }\n` +
        `}\n\nexport {};\n`
    );
}

// the indexed access defers resolution. an `extends Pick<typeof Bot, ...>` clause resolves while the bot
// constant is still being inferred, and a plugin ctor naming Core closes that loop (TS7022).
function renderPluginRows(keys: readonly string[]): string {
    return keys.map((key) => `        ${renderKey(key)}: (typeof ${BOT_BINDING})['${escapeLiteral(key)}'];`).join('\n');
}

function renderSlashRows(tables: SlashTables): string {
    return Object.entries(tables)
        .sort(([first], [second]) => compare(first, second))
        .map(([route, row]) => `        ${renderKey(route)}: ${renderRow(row)};`)
        .join('\n');
}

function renderContextMenuRows(menus: ContextMenuTables): string {
    return Object.entries(menus)
        .sort(([first], [second]) => compare(first, second))
        .map(([name, { cache }]) => `        ${renderKey(name)}: ${renderCacheRow(cache)};`)
        .join('\n');
}

function renderCacheRow(cache: 'cached' | undefined): string {
    return `{ cache: ${cache === undefined ? 'undefined' : `'${cache}'`} }`;
}

// InjectedEmojiMap reads this tag to type Emojis.X as GuildEmoji or ApplicationEmoji
function renderEmojiRows(emojis: EmojiKinds): string {
    return Object.entries(emojis)
        .sort(([first], [second]) => compare(first, second))
        .map(([key, kind]) => `        ${renderKey(key)}: '${kind === 'tuple' ? 'guild' : 'application'}';`)
        .join('\n');
}

function renderRow(row: SlashRouteEntry): string {
    const cache = row.cache === undefined ? 'undefined' : `'${row.cache}'`;
    return `{ options: ${renderOptions(row.options)}; cache: ${cache} }`;
}

function renderOptions(options: RouteOptions): string {
    const entries = Object.entries(options);
    if (entries.length === 0) return '{}';
    return `{ ${entries.map(([name, opt]) => `${renderKey(name)}: ${renderOption(opt)}`).join('; ')} }`;
}

function renderOption(opt: SlashOption): string {
    const parts = [`kind: '${opt.kind}'`, `required: ${opt.required}`];
    if (opt.choices && opt.choices.length > 0) parts.push(`choices: [${opt.choices.map(renderChoice).join(', ')}]`);
    if (opt.autocomplete) parts.push('autocomplete: true');
    // wire numbers, mapped to channel subtypes by the typed view
    if (opt.channelTypes && opt.channelTypes.length > 0) parts.push(`channelTypes: [${opt.channelTypes.join(', ')}]`);
    return `{ ${parts.join('; ')} }`;
}

function renderChoice(value: string | number): string {
    if (typeof value !== 'string') return String(value);
    return `'${escapeLiteral(value)}'`;
}

// discord allows spaces and apostrophes in a context-menu name
function renderKey(name: string): string {
    return IDENTIFIER.test(name) ? name : `'${escapeLiteral(name)}'`;
}

function escapeLiteral(value: string): string {
    let escaped = '';
    for (const char of value) {
        const code = char.charCodeAt(0);
        switch (char) {
            case '\\': {
                escaped += '\\\\';
                break;
            }
            case "'": {
                escaped += String.raw`\'`;
                break;
            }
            case '\n': {
                escaped += String.raw`\n`;
                break;
            }
            case '\r': {
                escaped += String.raw`\r`;
                break;
            }
            case '\t': {
                escaped += String.raw`\t`;
                break;
            }
            default: {
                if (code < CONTROL_CHAR) escaped += String.raw`\x${code.toString(HEX_RADIX).padStart(2, '0')}`;
                else escaped += char;
            }
        }
    }
    return escaped;
}

function compare(first: string, second: string): number {
    if (first < second) return -1;
    return first > second ? 1 : 0;
}
