import { ChannelType } from 'discord-api-types/v10';
import { describe, it, expect } from 'vitest';

import { renderAugmentation } from '#commands/codegen/renderAugmentation';

import type { RouteOptions, SlashTables } from '#commands/codegen/AugmentationBuilder';

const AUGMENT_TARGET = '@seedcord/gateway';

function renderWithTarget(registry: Parameters<typeof renderAugmentation>[0]): string {
    return renderAugmentation(registry, AUGMENT_TARGET);
}

// most assertions only exercise the option tables, so wrap each route as a guild-only row
function guildRows(tables: Record<string, RouteOptions>): SlashTables {
    return Object.fromEntries(
        Object.entries(tables).map(([route, options]) => [route, { options, cache: 'cached' as const }])
    );
}

function renderSlash(tables: Record<string, RouteOptions>): string {
    return renderWithTarget({ slash: guildRows(tables), userContextMenus: {}, messageContextMenus: {}, emojis: {} });
}

type FlatRegistry = Omit<Parameters<typeof renderAugmentation>[0], 'slash'> & { slash: Record<string, RouteOptions> };

function renderSlashWith(registry: FlatRegistry, plugins?: Parameters<typeof renderAugmentation>[2]): string {
    return renderAugmentation({ ...registry, slash: guildRows(registry.slash) }, AUGMENT_TARGET, plugins);
}

describe('prettier shield', () => {
    it('shields the declare-module block from the consumer repo prettier', () => {
        const output = renderSlash({});
        expect(output).toContain("// prettier-ignore\ndeclare module '@seedcord/gateway' {");
    });
});

describe('renderAugmentation', () => {
    it('renders a flat command as a declare-module augmentation', () => {
        const output = renderSlash({
            ban: {
                target: { kind: 'user', required: true },
                reason: { kind: 'string', required: false }
            }
        });

        expect(output).toBe(
            `// Generated by \`seedcord codegen\`. Do not edit by hand.
// Run \`seedcord codegen\` after changing your commands, plugins, or emoji config.

// prettier-ignore
declare module '@seedcord/gateway' {
    interface SlashRegistry {
        ban: { options: { target: { kind: 'user'; required: true }; reason: { kind: 'string'; required: false } }; cache: 'cached' };
    }
    interface UserContextMenuRegistry {

    }
    interface MessageContextMenuRegistry {

    }
    interface EmojiMap {

    }
}

export {};
`
        );
    });

    it('sorts routes, quotes subcommand keys, renders choices and empty option sets (the --check contract)', () => {
        const output = renderSlash({
            'demo/setup': { channel: { kind: 'channel', required: true } },
            config: {
                scope: { kind: 'string', required: true, choices: ['guild', 'global'] },
                level: { kind: 'integer', required: false, choices: [1, 2] }
            },
            ping: {},
            ban: { target: { kind: 'user', required: true } }
        });

        expect(output).toBe(
            `// Generated by \`seedcord codegen\`. Do not edit by hand.
// Run \`seedcord codegen\` after changing your commands, plugins, or emoji config.

// prettier-ignore
declare module '@seedcord/gateway' {
    interface SlashRegistry {
        ban: { options: { target: { kind: 'user'; required: true } }; cache: 'cached' };
        config: { options: { scope: { kind: 'string'; required: true; choices: ['guild', 'global'] }; level: { kind: 'integer'; required: false; choices: [1, 2] } }; cache: 'cached' };
        'demo/setup': { options: { channel: { kind: 'channel'; required: true } }; cache: 'cached' };
        ping: { options: {}; cache: 'cached' };
    }
    interface UserContextMenuRegistry {

    }
    interface MessageContextMenuRegistry {

    }
    interface EmojiMap {

    }
}

export {};
`
        );
    });

    it('is byte-stable across renders regardless of input route order', () => {
        const first = renderSlash({ ban: {}, kick: {} });
        const second = renderSlash({ kick: {}, ban: {} });
        expect(first).toBe(second);
    });

    it('escapes an apostrophe in a string choice value and stays valid TS', () => {
        const output = renderSlash({
            survey: { answer: { kind: 'string', required: true, choices: ["don't", 'yes'] } }
        });

        expect(output).toContain(String.raw`choices: ['don\'t', 'yes']`);
    });

    it('escapes a backslash in a string choice value', () => {
        const output = renderSlash({
            path: { dir: { kind: 'string', required: true, choices: [String.raw`C:\Users`] } }
        });

        // input is C:\Users (one backslash); output literal doubles it to C:\\Users
        expect(output).toContain(String.raw`choices: ['C:\\Users']`);
    });

    it('escapes both a backslash and an apostrophe together', () => {
        const output = renderSlash({
            weird: { val: { kind: 'string', required: false, choices: [String.raw`it's a \test`] } }
        });

        // input: it's a \test  ->  literal: 'it\'s a \\test'
        expect(output).toContain(String.raw`choices: ['it\'s a \\test']`);
    });

    it('leaves a double-quote unescaped inside a single-quoted choice literal', () => {
        const output = renderSlash({
            quote: { phrase: { kind: 'string', required: true, choices: ['say "hi"'] } }
        });

        expect(output).toContain('choices: [\'say "hi"\']');
    });

    it('passes unicode choice values through unchanged', () => {
        const output = renderSlash({
            lang: { word: { kind: 'string', required: false, choices: ['café', 'naïve'] } }
        });

        expect(output).toContain("choices: ['café', 'naïve']");
    });

    it('escapes a newline in a string choice value', () => {
        const output = renderSlash({
            note: { tone: { kind: 'string', required: true, choices: ['a\nb'] } }
        });

        expect(output).toContain(String.raw`choices: ['a\nb']`);
        expect(output).not.toContain('a\nb');
    });

    it('quotes a route key and option name containing a hyphen', () => {
        const output = renderSlash({
            'my-command': { 'dry-run': { kind: 'boolean', required: false } }
        });

        expect(output).toContain("'my-command': {");
        expect(output).toContain("'dry-run': { kind: 'boolean'; required: false }");
    });

    it('renders the autocomplete flag on autocompletable options', () => {
        const output = renderSlash({
            search: {
                query: { kind: 'string', required: true, autocomplete: true },
                limit: { kind: 'integer', required: false, autocomplete: true }
            }
        });

        expect(output).toContain(
            "search: { options: { query: { kind: 'string'; required: true; autocomplete: true }; limit: { kind: 'integer'; required: false; autocomplete: true } }; cache: 'cached' };"
        );
    });

    it('renders declared channelTypes as wire numbers with no extra import', () => {
        const output = renderSlash({
            move: {
                dest: {
                    kind: 'channel',
                    required: true,
                    channelTypes: [ChannelType.GuildText, ChannelType.GuildAnnouncement]
                }
            }
        });

        expect(output).toBe(
            `// Generated by \`seedcord codegen\`. Do not edit by hand.
// Run \`seedcord codegen\` after changing your commands, plugins, or emoji config.

// prettier-ignore
declare module '@seedcord/gateway' {
    interface SlashRegistry {
        move: { options: { dest: { kind: 'channel'; required: true; channelTypes: [0, 5] } }; cache: 'cached' };
    }
    interface UserContextMenuRegistry {

    }
    interface MessageContextMenuRegistry {

    }
    interface EmojiMap {

    }
}

export {};
`
        );
    });

    it('renders number choices unquoted', () => {
        const output = renderSlash({
            level: {
                amount: { kind: 'number', required: true, choices: [0, -5, 3.14] },
                tier: { kind: 'integer', required: false, choices: [1, 2] }
            }
        });

        expect(output).toContain('choices: [0, -5, 3.14]');
        expect(output).toContain('choices: [1, 2]');
    });

    it('sorts routes by codepoint deterministically (case-sensitive)', () => {
        const output = renderSlash({
            z: {},
            a: {},
            Ban: {},
            _a: {},
            Z: {}
        });

        const order = [...output.matchAll(/^        ('?)([\w$/]+)\1: /gm)].map((m) => m[2]);
        // uppercase < underscore < lowercase by UTF-16 codepoint
        expect(order).toEqual(['Ban', 'Z', '_a', 'a', 'z']);
    });

    it('quotes subcommand route keys containing a slash and leaves plain keys unquoted', () => {
        const output = renderSlash({
            'demo/setup': { channel: { kind: 'channel', required: true } },
            config: { scope: { kind: 'string', required: false } }
        });

        expect(output).toContain("        'demo/setup': {");
        expect(output).toContain('        config: {');
        expect(output).not.toContain("'config'");
    });

    it('quotes an option name that is not a valid identifier', () => {
        const output = renderSlash({
            link: {
                'user-id': { kind: 'string', required: true },
                target: { kind: 'user', required: false }
            }
        });

        expect(output).toContain("'user-id': { kind: 'string'; required: true }");
        expect(output).toContain("target: { kind: 'user'; required: false }");
    });

    it('renders an empty option set as {}', () => {
        const output = renderSlash({ ping: {} });

        expect(output).toContain("        ping: { options: {}; cache: 'cached' };");
    });

    it('renders an empty registry as the banner, four empty interfaces, and export', () => {
        const output = renderSlashWith({
            slash: {},
            userContextMenus: {},
            messageContextMenus: {},
            emojis: {}
        });

        expect(output).toBe(
            `// Generated by \`seedcord codegen\`. Do not edit by hand.
// Run \`seedcord codegen\` after changing your commands, plugins, or emoji config.

// prettier-ignore
declare module '@seedcord/gateway' {
    interface SlashRegistry {

    }
    interface UserContextMenuRegistry {

    }
    interface MessageContextMenuRegistry {

    }
    interface EmojiMap {

    }
}

export {};
`
        );
    });

    it('is byte-stable across input order for a registry with options and choices', () => {
        const first = renderSlash({
            config: { scope: { kind: 'string', required: true, choices: ['guild', 'global'] } },
            ban: { target: { kind: 'user', required: true } }
        });
        const second = renderSlash({
            ban: { target: { kind: 'user', required: true } },
            config: { scope: { kind: 'string', required: true, choices: ['guild', 'global'] } }
        });

        expect(first).toBe(second);
    });

    it('renders the exact full-string contract for a realistic multi-route registry', () => {
        const output = renderSlash({
            'mod/ban': {
                target: { kind: 'user', required: true },
                reason: { kind: 'string', required: false, choices: ["don't", 'other'] }
            },
            settings: {
                scope: { kind: 'string', required: true, choices: ['guild', 'global'] },
                level: { kind: 'integer', required: false, choices: [1, 2] },
                'dry-run': { kind: 'boolean', required: false }
            },
            ping: {}
        });

        expect(output).toBe(
            `// Generated by \`seedcord codegen\`. Do not edit by hand.
// Run \`seedcord codegen\` after changing your commands, plugins, or emoji config.

// prettier-ignore
declare module '@seedcord/gateway' {
    interface SlashRegistry {
        'mod/ban': { options: { target: { kind: 'user'; required: true }; reason: { kind: 'string'; required: false; choices: ['don\\'t', 'other'] } }; cache: 'cached' };
        ping: { options: {}; cache: 'cached' };
        settings: { options: { scope: { kind: 'string'; required: true; choices: ['guild', 'global'] }; level: { kind: 'integer'; required: false; choices: [1, 2] }; 'dry-run': { kind: 'boolean'; required: false } }; cache: 'cached' };
    }
    interface UserContextMenuRegistry {

    }
    interface MessageContextMenuRegistry {

    }
    interface EmojiMap {

    }
}

export {};
`
        );
    });

    it('renders user and message context-menu names into their own interfaces, codepoint-sorted', () => {
        const output = renderSlashWith({
            slash: {},
            userContextMenus: { 'View Profile': { cache: 'cached' as const }, Report: { cache: 'cached' as const } },
            messageContextMenus: { 'Report Message': { cache: 'cached' as const }, Pin: { cache: 'cached' as const } },
            emojis: {}
        });

        expect(output).toBe(
            `// Generated by \`seedcord codegen\`. Do not edit by hand.
// Run \`seedcord codegen\` after changing your commands, plugins, or emoji config.

// prettier-ignore
declare module '@seedcord/gateway' {
    interface SlashRegistry {

    }
    interface UserContextMenuRegistry {
        Report: { cache: 'cached' };
        'View Profile': { cache: 'cached' };
    }
    interface MessageContextMenuRegistry {
        Pin: { cache: 'cached' };
        'Report Message': { cache: 'cached' };
    }
    interface EmojiMap {

    }
}

export {};
`
        );
    });

    it('emits the same name in both interfaces when a user and message command share it', () => {
        const output = renderSlashWith({
            slash: {},
            userContextMenus: { Report: { cache: 'cached' as const } },
            messageContextMenus: { Report: { cache: 'cached' as const } },
            emojis: {}
        });

        expect(output).toContain(
            "    interface UserContextMenuRegistry {\n        Report: { cache: 'cached' };\n    }"
        );
        expect(output).toContain(
            "    interface MessageContextMenuRegistry {\n        Report: { cache: 'cached' };\n    }"
        );
    });

    it('escapes an apostrophe in a context-menu name', () => {
        const output = renderSlashWith({
            slash: {},
            userContextMenus: { "Tony's Profile": { cache: 'cached' as const } },
            messageContextMenus: {},
            emojis: {}
        });

        expect(output).toContain(String.raw`        'Tony\'s Profile': { cache: 'cached' };`);
    });

    it('leaves an identifier-safe context-menu name unquoted', () => {
        const output = renderSlashWith({
            slash: {},
            userContextMenus: { Report: { cache: 'cached' as const } },
            messageContextMenus: {},
            emojis: {}
        });

        expect(output).toContain("        Report: { cache: 'cached' };");
        expect(output).not.toContain("'Report'");
    });

    it('is byte-stable across input order for the context-menu sets', () => {
        const first = renderSlashWith({
            slash: {},
            userContextMenus: { 'View Profile': { cache: 'cached' as const }, Report: { cache: 'cached' as const } },
            messageContextMenus: { Pin: { cache: 'cached' as const }, 'Report Message': { cache: 'cached' as const } },
            emojis: {}
        });
        const second = renderSlashWith({
            slash: {},
            userContextMenus: { Report: { cache: 'cached' as const }, 'View Profile': { cache: 'cached' as const } },
            messageContextMenus: { 'Report Message': { cache: 'cached' as const }, Pin: { cache: 'cached' as const } },
            emojis: {}
        });

        expect(first).toBe(second);
    });
});

describe('renderAugmentation plugin capabilities', () => {
    const empty = { slash: {}, userContextMenus: {}, messageContextMenus: {}, emojis: {} };

    it('imports the bot and augments Core with one member per attach key', () => {
        const output = renderAugmentation(empty, AUGMENT_TARGET, { specifier: './bot', keys: ['db', 'cache'] });

        expect(output).toBe(
            `// Generated by \`seedcord codegen\`. Do not edit by hand.
// Run \`seedcord codegen\` after changing your commands, plugins, or emoji config.

import type Bot from './bot';

// prettier-ignore
declare module '@seedcord/gateway' {
    interface Core {
        cache: (typeof Bot)['cache'];
        db: (typeof Bot)['db'];
    }
    interface SlashRegistry {

    }
    interface UserContextMenuRegistry {

    }
    interface MessageContextMenuRegistry {

    }
    interface EmojiMap {

    }
}

export {};
`
        );
    });

    it('emits no import and no Core block for a bot with no plugins', () => {
        const output = renderAugmentation(empty, AUGMENT_TARGET, { specifier: './bot', keys: [] });

        expect(output).toBe(renderAugmentation(empty, AUGMENT_TARGET));
        expect(output).not.toContain('import type');
        expect(output).not.toContain('interface Core');
    });

    it('is byte-stable across attach-key order', () => {
        const first = renderAugmentation(empty, AUGMENT_TARGET, { specifier: './bot', keys: ['db', 'cache'] });
        const second = renderAugmentation(empty, AUGMENT_TARGET, { specifier: './bot', keys: ['cache', 'db'] });

        expect(first).toBe(second);
    });

    it('quotes an attach key that is not a valid identifier', () => {
        const output = renderAugmentation(empty, AUGMENT_TARGET, { specifier: './bot', keys: ['my-db'] });

        expect(output).toContain("        'my-db': (typeof Bot)['my-db'];");
    });

    it('escapes an apostrophe in an attach key', () => {
        const output = renderAugmentation(empty, AUGMENT_TARGET, { specifier: './bot', keys: ["tony's"] });

        expect(output).toContain(String.raw`        'tony\'s': (typeof Bot)['tony\'s'];`);
    });

    it('carries the specifier through unchanged', () => {
        const output = renderAugmentation(empty, AUGMENT_TARGET, { specifier: '../src/bot', keys: ['db'] });

        expect(output).toContain("import type Bot from '../src/bot';");
    });

    it('escapes an apostrophe in the bot specifier', () => {
        const output = renderAugmentation(empty, AUGMENT_TARGET, { specifier: "./tony's/bot", keys: ['db'] });

        expect(output).toContain(String.raw`import type Bot from './tony\'s/bot';`);
    });

    it('escapes a backslash in the bot specifier', () => {
        const output = renderAugmentation(empty, AUGMENT_TARGET, { specifier: String.raw`./a\b/bot`, keys: ['db'] });

        expect(output).toContain(String.raw`import type Bot from './a\\b/bot';`);
    });
});

describe('renderAugmentation emoji rows', () => {
    it('renders emoji keys into EmojiMap, application for a string config and guild for a tuple config', () => {
        const output = renderSlashWith({
            slash: {},
            userContextMenus: {},
            messageContextMenus: {},
            emojis: { Confirm: 'string', Lol: 'tuple', Cancel: 'string' }
        });

        expect(output).toContain(
            "    interface EmojiMap {\n        Cancel: 'application';\n        Confirm: 'application';\n        Lol: 'guild';\n    }"
        );
    });

    it('quotes an emoji key that is not a valid identifier', () => {
        const output = renderSlashWith({
            slash: {},
            userContextMenus: {},
            messageContextMenus: {},
            emojis: { 'thumbs-up': 'string' }
        });

        expect(output).toContain("        'thumbs-up': 'application';");
    });

    it('escapes an apostrophe in an emoji key', () => {
        const output = renderSlashWith({
            slash: {},
            userContextMenus: {},
            messageContextMenus: {},
            emojis: { "Tony's": 'string' }
        });

        expect(output).toContain(String.raw`        'Tony\'s': 'application';`);
    });

    it('is byte-stable across input order for the emoji keys', () => {
        const first = renderSlashWith({
            slash: {},
            userContextMenus: {},
            messageContextMenus: {},
            emojis: { Confirm: 'string', Lol: 'tuple' }
        });
        const second = renderSlashWith({
            slash: {},
            userContextMenus: {},
            messageContextMenus: {},
            emojis: { Lol: 'tuple', Confirm: 'string' }
        });

        expect(first).toBe(second);
    });
});
