name: lint-actions

on:
    pull_request:
        paths:
            - '.github/workflows/**'
            - '.github/actions/**'
    push:
        branches:
            - main
            - next
        paths:
            - '.github/workflows/**'
            - '.github/actions/**'

permissions:
    contents: read

jobs:
    actionlint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
            - name: actionlint
              run: |
                  curl -sSfL https://raw.githubusercontent.com/rhysd/actionlint/v1.7.12/scripts/download-actionlint.bash | bash -s -- 1.7.12
                  ./actionlint -color
